@startuml
skinparam backgroundColor #f5f5f5
skinparam componentStyle rectangle
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
    RoundCorner 15
}

component "<UI>\nAppRoomEasy\n--------\nFormulario Reserva" as AppRoomEasy

component "<AUI>\nPantallaLogin" as PantallaLogin

component "<SERVICIO>\nGestorReserva" as GestorReserva
component "<Servicio>\nGestorCliente" as GestorCliente

component "<DAO>\nReservaDAO" as ReservaDAO
component "<DAO>\nClienteDAO" as ClienteDAO1
component "ClienteDAO" as ClienteDAO2

component "ConexionBD" as ConexionBD
database "BaseDeDatosMySQL\n--\nCLIENTE,\nRESERVA,\nHABITACION,\nETC." as BD

AppRoomEasy --> GestorReserva
GestorReserva --> ReservaDAO
ReservaDAO --> ClienteDAO1
PantallaLogin --> GestorCliente
GestorCliente --> ConexionBD
ConexionBD --> ClienteDAO2
ClienteDAO1 --> BD
ClienteDAO2 --> BD
ReservaDAO --> ConexionBD

@enduml